### PR TITLE
Updated To use EarlyBoundGenerator.Api.

### PR DESCRIPTION
**Pull request by daryllabar**
PR for Integrate EarlyBound Generator #378

Removed Previous CrmSvcUtil Utilities.
Mapped all settings of earlyboundtypes except generateStateEnums and GenerateGlobalOptionSets.   There are no settings currently for this in the EarlyBoundGenerator, and I can't think of a good reason why you would not want to include these.

Updated EarlyBoundTypeConfig to inherit from DLaB.EarlyBoundGeneator.Settings.POCO.ExtensionConfig.  This means all settings in the EarlyBoundGenerator will be allowed (except it they are overriden with the current settings of the EarlyBoundTypeConfig.  Also added names for the action, and optionSet.

Updated Tests.

Updated VS.  Not sure that matters...

### CODE REVIEW

**Comment by daryllabar** [comment]
There are two breaking change.
 1. No longer able to control not generating State/status optionsets and global option sets separately.  
 2. The casing for the OptionSetEnums are based on the schema, not the logical names.  Much more readable, but, a breaking change for where ever it is referenced...

**Comment by scottdurow** [comment]
Thanks fo this @daryllabar - rather than introduce breaking changes - there needs to be a switch to either use your filtering service - or the existing spkl one to preserve existing projects.

**Comment by daryllabar** [comment]
Ok, if we are going to have a switch, then would it make sense to have a completely different JSON section for it so there is no mapping required?

And if so, I didn't see anywhere where the JSON config is parsed.  If I added an entirely new node to the JSON, would I need to add any code to handle that?

**Comment by daryllabar** [comment]
Also question, why do you care about breaking change #1?  What is the reason you'd not want to generate globals and or state/status enums?  If I see a good reason for it, then I may just add it to the EBG.

**Comment by scottdurow** [comment]
1. We care about breaking changes because it could break people's builds! 😋
1. Can you change the pull request to target the [spkl_dev](https://github.com/scottdurow/SparkleXrm/tree/spkl_dev/spkl) branch
1. Yes - default to the existing filtering service
1. Just add any additional config flags to the existing [Earlybound config](https://github.com/scottdurow/SparkleXrm/blob/spkl_dev/spkl/SparkleXrm.Tasks/Config/EarlyBoundTypeConfig.cs)  - along with a switch (e.g. something like useEarlyBoundGeneratorApi)
1. config is loaded using `Newtonsoft.Json.JsonConvert.DeserializeObject` https://github.com/scottdurow/SparkleXrm/blob/35b23c29ccaefd46ae51efe92f8b12e734eaf855/spkl/SparkleXrm.Tasks/Config/ConfigFile.cs#L175

**Pull request closed without merging**
