### PR TITLE
Update to use login control to support MFA

### PR DESCRIPTION
**Pull request by aelsmore**
This pull request is to change the manual login mechanism to use the SDK login control. This enables support for MFA using either OrganizationServiceProxy or OrganizationWebServiceProxy

### CODE REVIEW

**Comment by scottdurow** [comment]
This is cool - so it will popup and do an interactive login. Does this PR still support the legacy console login mechanism?

**Comment by aelsmore** [comment]
Hi @scottdurow 
Yes, if the connection string is provided in the command line, it should use that instead of the interactive form.

**Comment by scottdurow** [comment]
Ok - yeah - but also some folks will still want to use the saved username/password logins like it does currently - don't want to break that just yet!

**Comment by aelsmore** [comment]
Hmmm.... add a -legacylogin command param?

**Comment by teppolainio** [comment]
Is there really need for separate MFA window included within spkl? XRM.Tooling supports connection string parameter `LoginPrompt` which allows user to decide on connection string if he want's to have interactive SDK login window and SDK login window supports MFA out of the box. It has to be noted this option is applicable only with OAuth. There is even following note on SDK documentation:
> OAuth is the preferred auth type for connecting to Common Data Service when using a interactive flow. This auth type fully supports the features of Azure Active Directory Conditional Access and Multi-Factor authentication.

On [XRM tooling connection string documentation](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect#connection-string-parameters) there is example "_OAuth using current logged in user with fall back UX to prompt for authentication_"  with following connection string: `AuthType=OAuth;   Username=jsmith@contoso.onmicrosoft.com; Integrated Security=true;  Url=https://contosotest.crm.dynamics.com; AppId=51f81489-12ee-4a9e-aaae-a2591f45987d;  RedirectUri=app://58145B91-0C36-4500-8554-080854F2AC97;   TokenCacheStorePath=c:\MyTokenCache;  LoginPrompt=Auto`.
You can set SDK login prompt to jump up every time by using `LoginPromt=Always`.

I'd stay with XRM.Tooling and add support for using its features for MFA. I guess it should be pretty easy to make transition to XRM tooling connection strings as a non-breaking change.

**Comment by scottdurow** [comment]
There are two modes to the auth/login:
- Connection Strings (used usually for CI/CD pipelines) - this already uses the Xrm tooling assemblies as I'm sure you know
- Interactive login mode - where you can connect via the commandline prompts - used on a developer workstation. The advantage of this is that it will remember the login credentials and allows you to select from a previously added list of orgs.

We need to preserve both modes - This PR is for the interactive login mode - and I really want to ensure that we keep the simplicity of this mode for developers - so that they don't need to login everytime they want to deploy if they have chosen to save credentials.

@teppolainio  I agree that we don't need a separate Login window because the Tooling provides one already - it also has the ability to store tokens in the token cache. So really, we just need a console UX around saved tokens and selecting the org to connect to. The tooling will do the rest.

**Comment by scottdurow** [comment]
This is what I am proposing we use - https://github.com/scottdurow/SparkleXrm/tree/features/use-xrmtooling
@teppolainio @aelsmore  any comments?

**Comment by teppolainio** [comment]
@scottdurow your suggestion seems to basically be what I was thinking of.

One thing which needs to be done in addition to #373 is to update all CrmSdk NuGets to newest version. Microsoft has updated SDK so that following connectionstring fails with NullReferenceException from SDK due to missing EnvironmentId property. This connection string is very nice from desktop because it defaults to current user credentials and you can put this connection string to version control for every developer to use.
`AuthType = OAuth; Integrated Security = true; Url = https://replaceWithCorrectOrg.crm4.dynamics.com; AppId=51f81489-12ee-4a9e-aaae-a2591f45987d; RedirectUri=app://58145B91-0C36-4500-8554-080854F2AC97; LoginPrompt=Auto`

**Comment by scottdurow** [comment]
This, of course, will only work for Online Environments - to work with OnPrem we would need to use the Login control as @aelsmore has shown in this PR - I think for now we can have folks just use the legacy login mode in spkl. I'll add a note to the top of the login prompt explaining that.

**Pull request closed without merging**
