### PR TITLE
Support writing of custom API attributes and test refactoring

### PR DESCRIPTION
**Pull request by bermo**
Even though the Custom API support is probably not fully baked yet, noticed that the attributes were not being written properly during an `instrument` - have attempted to fix this.
When running the integration tests to try and help determine if I'd broken anything, I noticed lots of issues! I have attempted to fix the broken integration tests and make the integration tests generally less brittle. 
I would recommend splitting the unit/integration tests into two separate projects to make them easier to manage, but didn't want to change too much ...

### CODE REVIEW

**Comment by scottdurow** [comment]
Thanks for this. Can you change the target branch to be spkl_dev please. This is the development branch.

**Comment by bermo** [comment]
Sorry, I did develop against spkl_dev, but it must default to master or something when pull requests on forks are created - my bad.

**Comment by scottdurow** [comment]
Thanks for this - I've included the Custom Api instrumentation changes in #419.
I do agree about the integration tests being somewhat fragile - and would be better off in a separate project rather than using the Trait/playlist approach.

**Comment by scottdurow** [comment]
Released in Fixed in https://www.nuget.org/packages/spkl/1.0.633-beta

**Pull request closed without merging**
