### PR TITLE
Update spkl Program.cs to use CrmServiceClient.MaxConnectionTimeout

### PR DESCRIPTION
**Pull request by rtebar**
Hi @scottdurow 

Hope the Covid-19 situation is not affecting you & family.

I have created this PR to use **CrmServiceClient.MaxConnectionTimeout** instead of OrganizationServiceProxy.

Before this change, I was trying to use the **ClientSecret authentication** and the OrganizationServiceProxy was null, so that the library was failing.

Since [OrganizationServiceProxy  is getting deprecated](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-common-data-service), I have replaced it by CrmServiceClient.MaxConnectionTimeout. 

In order to use MaxConnectionTimeout, I have also updated the XrmTooling Nuget packages and their references.

### CODE REVIEW

**Comment by scottdurow** [comment]
Thanks for this @rtebar  - can change your source branch to be spkl_dev - this is the v.next beta branch.

**Comment by rtebar** [comment]
No problem @scottdurow, I'll close this PR and I'll create a new one. So the the commit should be from  rtebar:spkl_dev into scottdurow:spkl_dev, right?

**Comment by scottdurow** [comment]
Yes - that's right! You should then see only the diffs that you have made in the 'Files changed'

**Comment by rtebar** [comment]
Hi @scottdurow, while I was syncing my original fork, I noticed the same change that I was submitting was already implemented in the dev branch :) So no need for my pull request. 

Then I also realised that you have published the latest changes in Nuget and I understand that https://www.nuget.org/packages/spkl/**1.0.394-beta** already contains the feature I was looking for. So I'm going to test it and I'll let you know if I find any issue. 

Thanks!

**Pull request closed without merging**
