### PR TITLE
Invalid OptionSet Names 

### PR DESCRIPTION
**Pull request by JannyM85**
Hi, when generate optionSets earlyboundtypes from CRM and the base language is differetn from EN then you have probelm with EarlyBoundTypes-Optonset name for example : 

[System.Runtime.Serialization.DataContractAttribute()]	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum account_preferredcontactmethodcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel1 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel2 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel3 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel4 = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel5 = 5,
	}
My PR add to soltuion NamingService which change default generating style and add support for different languages.
I want to fix this issue #349

### CODE REVIEW

**Comment by scottdurow** [comment]
Thanks for this PR - can you describe the issue that this is fixing in a bit more detail in an issue and then associate the Issue to the PR.
Also - can you rebase the PR onto the spkl_dev branch.
Thank you

**Comment by JannyM85** [comment]
I change description in first comment. It is ok now?

**Comment by teppolainio** [comment]
Out of curiosity what's the reason of normalizing optionset labels to fit into regex pattern ^[A-Za-z_][A-Za-z0-9_]*$ even though this isn't necessary? In my previous workplace I made quite a similar extension quite a while ago which took characters as such which ensured labels in code were (almost) exactly like they were on UI. .NET languages do not any issues in coping with UTF-8 enum labels so optionse labels like "Päätös" works flawlessly as enum value "Päätös".

I'd vote for keeping enum labels on code as close as how they are put in customizations because that reduces possibilities of human errors (and also need to check things as much).

One possiblity would be to make language code argument to have another parameter which controls if label is normalized or not. I of course vote default not to be normalized.

**Comment by teppolainio** [comment]
I did some research and it seems I confused normalization with transliteration. Transliteration could've made some words like "Määräpäivä" pretty unreadable ("Maeaeraepaeivae").

**Comment by JannyM85** [comment]
I create differrent pull request.

**Pull request closed without merging**
