### PR TITLE
Support for deployment of  WorkflowActivity class which inherits from Custom Base class

### PR DESCRIPTION
**Pull request by sabrish**
Support for deployment of  WorkflowActivity class which inherits from Custom class which inherits from CodeActivity. (e.g support for deployment of workflows inheriting from WorkflowActivityBase class)

This code supports Workflow Activities which inherit from CodeActivity or any Custom Class such as WorkflowActivityBase which inherits from CodeActivity

### CODE REVIEW

**Comment by scottdurow** [comment]
Is there meant to be a unit test that uses WorkflowActivityInheritingFromWorkflowActivityBase.cs ?

**Comment by sabrish** [comment]
@scottdurow  i did look in the existing test code to find an example wrt how you want the unit test code written. There was only integration test for deploying workflow activities. And since that was assembly specific I didn't add anything.

**Comment by sabrish** [comment]
@scottdurow sorry to chase... could I ask when this will be merged and released?

**Comment by scottdurow** [comment]
I’m on it this week!

**Comment by sabrish** [comment]
@scottdurow - thanks a lot

**Comment by scottdurow** [comment]
Included in https://www.nuget.org/packages/spkl/1.0.206-beta

**Pull request merged**
